-- The same product source used by opf_shift_reconciliation.sql.
-- Production transaction time anchors the report; assay sample time is separate.
WITH params AS (
    SELECT TO_TIMESTAMP_TZ(%s) AS START_TS, TO_TIMESTAMP_TZ(%s) AS END_TS,
           PARSE_JSON(%s) AS OPFS
), selected_opfs AS (
    SELECT VALUE::VARCHAR AS OPF FROM params, LATERAL FLATTEN(INPUT => params.OPFS)
), records AS (
    SELECT
        CASE UPPER(TRIM(SOURCE))
            WHEN 'CCOPF01' THEN 'CC_OPF01' WHEN 'CCOPF02' THEN 'CC_OPF02'
            WHEN 'CBOPF' THEN 'CB_OPF' WHEN 'EWOPF' THEN 'EW_OPF'
            WHEN 'FTOPF' THEN 'FT_OPF' WHEN 'VOKOPF' THEN 'VK_OPF'
            ELSE UPPER(TRIM(SOURCE))
        END AS OPF,
        UPPER(TRIM(MOVEMENT_PRODUCT)) AS BRAND,
        CONVERT_TIMEZONE('Australia/Perth', TRANSACTION_DATETIME)::TIMESTAMP_NTZ AS OBSERVED_AT,
        CONVERT_TIMEZONE('Australia/Perth', SAMPLED_AT_DATETIME)::TIMESTAMP_NTZ AS SAMPLED_AT,
        CONVERT_TIMEZONE('Australia/Perth', LAST_UPDATE)::TIMESTAMP_NTZ AS LAST_UPDATED,
        CONVERT_TIMEZONE('Australia/Perth', START_DATETIME)::TIMESTAMP_NTZ AS PERIOD_START,
        CONVERT_TIMEZONE('Australia/Perth', END_DATETIME)::TIMESTAMP_NTZ AS PERIOD_END,
        SHIFT_DATE, SHIFT, BUILD, DESTINATION, DMT, WMT, FE, SIO2, AL2O3, P, MN
    FROM AA_OPERATIONS_MANAGEMENT.SELFSERVICE.INVENTORY_OPF_PRODUCT, params
    WHERE TRANSACTION_DATETIME >= params.START_TS AND TRANSACTION_DATETIME < params.END_TS
      AND SHIFT_DATE >= DATEADD(day, -1, TO_DATE(params.START_TS))
      AND SHIFT_DATE <= TO_DATE(params.END_TS)
)
SELECT records.* FROM records JOIN selected_opfs ON records.OPF = selected_opfs.OPF
ORDER BY OBSERVED_AT, records.OPF, BRAND, BUILD, DESTINATION
LIMIT 200001
