WITH opf_feed_raw AS (
    SELECT
        CASE
            WHEN DESTINATION LIKE 'OP1_%' THEN 'CC_OPF01'
            WHEN DESTINATION LIKE 'OP2_%' THEN 'CC_OPF02'
            WHEN DESTINATION LIKE 'HOP_%' THEN 'CB_OPF'
            WHEN DESTINATION = 'EW_BN1' THEN 'EW_OPF'
            WHEN DESTINATION LIKE 'IB_PC%' THEN 'IB_OPF'
            WHEN DESTINATION LIKE 'FTN_%' THEN 'FT_OPF'
            WHEN DESTINATION LIKE 'VOK_%' OR DESTINATION LIKE 'VOQ_%' THEN 'VK_OPF'
            ELSE OPERATION || '_UNKNOWN'
        END AS DERIVED_OPERATION,
        SHIFT_DATE,
        SUM(WMT_REPORTING) AS FEED_WMT,
        SUM(FE * WMT_REPORTING) / NULLIF(SUM(WMT_REPORTING), 0) AS MOD_ROM_FE,
        SUM(SIO2 * WMT_REPORTING) / NULLIF(SUM(WMT_REPORTING), 0) AS MOD_ROM_SIO2,
        SUM(AL2O3 * WMT_REPORTING) / NULLIF(SUM(WMT_REPORTING), 0) AS MOD_ROM_AL2O3,
        SUM(P * WMT_REPORTING) / NULLIF(SUM(WMT_REPORTING), 0) AS MOD_ROM_P,
        SUM(MN * WMT_REPORTING) / NULLIF(SUM(WMT_REPORTING), 0) AS MOD_ROM_MN,
        SUM(PROD1_FE * WMT_REPORTING) / NULLIF(SUM(WMT_REPORTING), 0) AS MOD_PROD1_FE,
        SUM(PROD1_SIO2 * WMT_REPORTING) / NULLIF(SUM(WMT_REPORTING), 0) AS MOD_PROD1_SIO2,
        SUM(PROD1_AL2O3 * WMT_REPORTING) / NULLIF(SUM(WMT_REPORTING), 0) AS MOD_PROD1_AL2O3,
        SUM(PROD1_P * WMT_REPORTING) / NULLIF(SUM(WMT_REPORTING), 0) AS MOD_PROD1_P,
        SUM(PROD1_MN * WMT_REPORTING) / NULLIF(SUM(WMT_REPORTING), 0) AS MOD_PROD1_MN,
        SUM(PROD2_FE * WMT_REPORTING) / NULLIF(SUM(WMT_REPORTING), 0) AS MOD_PROD2_FE,
        SUM(PROD2_SIO2 * WMT_REPORTING) / NULLIF(SUM(WMT_REPORTING), 0) AS MOD_PROD2_SIO2,
        SUM(PROD2_AL2O3 * WMT_REPORTING) / NULLIF(SUM(WMT_REPORTING), 0) AS MOD_PROD2_AL2O3,
        SUM(PROD2_P * WMT_REPORTING) / NULLIF(SUM(WMT_REPORTING), 0) AS MOD_PROD2_P,
        SUM(PROD2_MN * WMT_REPORTING) / NULLIF(SUM(WMT_REPORTING), 0) AS MOD_PROD2_MN
    FROM AA_OPERATIONS_MANAGEMENT.SELFSERVICE.INVENTORY_EXPIT_REHANDLE_TRANSACTIONS
    WHERE SHIFT_DATE >= %s AND SHIFT_DATE < %s
      AND IS_DELETED = FALSE
      AND MOVEMENT_CLASSIFICATION = 'Rehandle Ore'
      AND MOVEMENT_SUBCLASSIFICATION = 'Rehandle Ore Primary'
    GROUP BY 1, SHIFT_DATE
),
opf_feed AS (
    SELECT *,
        IFF(DERIVED_OPERATION IN ('CC_OPF02', 'VK_OPF'), MOD_PROD2_FE, MOD_PROD1_FE) AS MOD_PROD_FE,
        IFF(DERIVED_OPERATION IN ('CC_OPF02', 'VK_OPF'), MOD_PROD2_SIO2, MOD_PROD1_SIO2) AS MOD_PROD_SIO2,
        IFF(DERIVED_OPERATION IN ('CC_OPF02', 'VK_OPF'), MOD_PROD2_AL2O3, MOD_PROD1_AL2O3) AS MOD_PROD_AL2O3,
        IFF(DERIVED_OPERATION IN ('CC_OPF02', 'VK_OPF'), MOD_PROD2_P, MOD_PROD1_P) AS MOD_PROD_P,
        IFF(DERIVED_OPERATION IN ('CC_OPF02', 'VK_OPF'), MOD_PROD2_MN, MOD_PROD1_MN) AS MOD_PROD_MN
    FROM opf_feed_raw
),
opf_product AS (
    SELECT
        CASE
            WHEN SOURCE = 'CCOPF01' THEN 'CC_OPF01'
            WHEN SOURCE = 'CCOPF02' THEN 'CC_OPF02'
            WHEN SOURCE = 'CBOPF' THEN 'CB_OPF'
            WHEN SOURCE = 'EWOPF' THEN 'EW_OPF'
            WHEN SOURCE = 'FTOPF' THEN 'FT_OPF'
            WHEN SOURCE = 'VOKOPF' THEN 'VK_OPF'
            ELSE SOURCE
        END AS DERIVED_OPERATION,
        UPPER(TRIM(MOVEMENT_PRODUCT)) AS BRAND,
        SHIFT_DATE,
        SUM(DMT) AS PROD_DMT,
        SUM(WMT) AS PROD_WMT,
        SUM(FE * DMT) / NULLIF(SUM(DMT), 0) AS PROD_FE,
        SUM(SIO2 * DMT) / NULLIF(SUM(DMT), 0) AS PROD_SIO2,
        SUM(AL2O3 * DMT) / NULLIF(SUM(DMT), 0) AS PROD_AL2O3,
        SUM(P * DMT) / NULLIF(SUM(DMT), 0) AS PROD_P,
        SUM(MN * DMT) / NULLIF(SUM(DMT), 0) AS PROD_MN
    FROM AA_OPERATIONS_MANAGEMENT.SELFSERVICE.INVENTORY_OPF_PRODUCT
    WHERE SHIFT_DATE >= %s AND SHIFT_DATE < %s
    GROUP BY 1, 2, SHIFT_DATE
),
opf_product_total AS (
    SELECT DERIVED_OPERATION, SHIFT_DATE, SUM(PROD_DMT) AS TOTAL_PROD_DMT
    FROM opf_product
    GROUP BY 1, 2
),
opf_tails AS (
    SELECT
        CASE
            WHEN SOURCE = 'CCOPF01' THEN 'CC_OPF01'
            WHEN SOURCE = 'CCOPF02' THEN 'CC_OPF02'
            WHEN SOURCE = 'CBOPF' THEN 'CB_OPF'
            WHEN SOURCE = 'VOKOPF' THEN 'VK_OPF'
            ELSE SOURCE
        END AS DERIVED_OPERATION,
        SHIFT_DATE,
        SUM(DMT) AS TAILS_DMT,
        SUM(FE * DMT) / NULLIF(SUM(DMT), 0) AS TAILS_FE,
        SUM(SIO2 * DMT) / NULLIF(SUM(DMT), 0) AS TAILS_SIO2,
        SUM(AL2O3 * DMT) / NULLIF(SUM(DMT), 0) AS TAILS_AL2O3,
        SUM(P * DMT) / NULLIF(SUM(DMT), 0) AS TAILS_P,
        SUM(MN * DMT) / NULLIF(SUM(DMT), 0) AS TAILS_MN
    FROM AA_OPERATIONS_MANAGEMENT.SELFSERVICE.INVENTORY_OPF_TAILS
    WHERE SHIFT_DATE >= %s AND SHIFT_DATE < %s
    GROUP BY 1, SHIFT_DATE
),
allocated AS (
    SELECT p.*, 
        COALESCE((p.PROD_DMT / NULLIF(pt.TOTAL_PROD_DMT, 0)) * t.TAILS_DMT, 0) AS TAILS_DMT_ALLOC,
        t.TAILS_FE, t.TAILS_SIO2, t.TAILS_AL2O3, t.TAILS_P, t.TAILS_MN
    FROM opf_product p
    LEFT JOIN opf_product_total pt USING (DERIVED_OPERATION, SHIFT_DATE)
    LEFT JOIN opf_tails t USING (DERIVED_OPERATION, SHIFT_DATE)
),
back_calc AS (
    SELECT *,
        (PROD_DMT * PROD_FE + TAILS_DMT_ALLOC * COALESCE(TAILS_FE, 0)) / NULLIF(PROD_DMT + TAILS_DMT_ALLOC, 0) AS BACK_CALC_FE,
        (PROD_DMT * PROD_SIO2 + TAILS_DMT_ALLOC * COALESCE(TAILS_SIO2, 0)) / NULLIF(PROD_DMT + TAILS_DMT_ALLOC, 0) AS BACK_CALC_SIO2,
        (PROD_DMT * PROD_AL2O3 + TAILS_DMT_ALLOC * COALESCE(TAILS_AL2O3, 0)) / NULLIF(PROD_DMT + TAILS_DMT_ALLOC, 0) AS BACK_CALC_AL2O3,
        (PROD_DMT * PROD_P + TAILS_DMT_ALLOC * COALESCE(TAILS_P, 0)) / NULLIF(PROD_DMT + TAILS_DMT_ALLOC, 0) AS BACK_CALC_P,
        (PROD_DMT * PROD_MN + TAILS_DMT_ALLOC * COALESCE(TAILS_MN, 0)) / NULLIF(PROD_DMT + TAILS_DMT_ALLOC, 0) AS BACK_CALC_MN
    FROM allocated
)
SELECT
    f.DERIVED_OPERATION, b.BRAND, f.SHIFT_DATE, f.FEED_WMT, b.PROD_WMT,
    b.BACK_CALC_FE / NULLIF(f.MOD_ROM_FE, 0) AS BLEND_RECON_FE,
    b.BACK_CALC_SIO2 / NULLIF(f.MOD_ROM_SIO2, 0) AS BLEND_RECON_SIO2,
    b.BACK_CALC_AL2O3 / NULLIF(f.MOD_ROM_AL2O3, 0) AS BLEND_RECON_AL2O3,
    b.BACK_CALC_P / NULLIF(f.MOD_ROM_P, 0) AS BLEND_RECON_P,
    b.BACK_CALC_MN / NULLIF(f.MOD_ROM_MN, 0) AS BLEND_RECON_MN,
    IFF(f.DERIVED_OPERATION IN ('EW_OPF', 'FT_OPF'), 1.0,
        (b.PROD_FE / NULLIF(b.BACK_CALC_FE, 0)) / NULLIF(f.MOD_PROD_FE / NULLIF(f.MOD_ROM_FE, 0), 0)) AS REGRESSION_RECON_FE,
    IFF(f.DERIVED_OPERATION IN ('EW_OPF', 'FT_OPF'), 1.0,
        (b.PROD_SIO2 / NULLIF(b.BACK_CALC_SIO2, 0)) / NULLIF(f.MOD_PROD_SIO2 / NULLIF(f.MOD_ROM_SIO2, 0), 0)) AS REGRESSION_RECON_SIO2,
    IFF(f.DERIVED_OPERATION IN ('EW_OPF', 'FT_OPF'), 1.0,
        (b.PROD_AL2O3 / NULLIF(b.BACK_CALC_AL2O3, 0)) / NULLIF(f.MOD_PROD_AL2O3 / NULLIF(f.MOD_ROM_AL2O3, 0), 0)) AS REGRESSION_RECON_AL2O3,
    IFF(f.DERIVED_OPERATION IN ('EW_OPF', 'FT_OPF'), 1.0,
        (b.PROD_P / NULLIF(b.BACK_CALC_P, 0)) / NULLIF(f.MOD_PROD_P / NULLIF(f.MOD_ROM_P, 0), 0)) AS REGRESSION_RECON_P,
    IFF(f.DERIVED_OPERATION IN ('EW_OPF', 'FT_OPF'), 1.0,
        (b.PROD_MN / NULLIF(b.BACK_CALC_MN, 0)) / NULLIF(f.MOD_PROD_MN / NULLIF(f.MOD_ROM_MN, 0), 0)) AS REGRESSION_RECON_MN
FROM opf_feed f
LEFT JOIN back_calc b USING (DERIVED_OPERATION, SHIFT_DATE)
ORDER BY f.DERIVED_OPERATION, b.BRAND, f.SHIFT_DATE
