-- ROM inbound ore only. Classifications verified against the live warehouse.
WITH params AS (
    SELECT TO_TIMESTAMP_TZ(%s) AS START_TS, TO_TIMESTAMP_TZ(%s) AS END_TS,
           %s AS OPERATION_NAME, PARSE_JSON(%s) AS DESTINATIONS
)
SELECT INTERNAL_ID, OPERATION, SOURCE, SOURCE_FMS, DESTINATION, DESTINATION_FMS,
       CONVERT_TIMEZONE('Australia/Perth', TRANSACTION_DATETIME)::TIMESTAMP_NTZ AS OBSERVED_AT,
       WMT_REPORTING AS WMT, MOVEMENT_TYPE, MOVEMENT_CLASSIFICATION, MOVEMENT_SUBCLASSIFICATION
FROM AA_OPERATIONS_MANAGEMENT.SELFSERVICE.INVENTORY_EXPIT_REHANDLE_TRANSACTIONS
CROSS JOIN params
WHERE TRANSACTION_DATETIME >= params.START_TS AND TRANSACTION_DATETIME < params.END_TS
  AND UPPER(TRIM(OPERATION)) = params.OPERATION_NAME
  AND UPPER(TRIM(DESTINATION_FMS)) IN (SELECT VALUE::STRING FROM TABLE(FLATTEN(INPUT => params.DESTINATIONS)))
  AND IS_DELETED = FALSE
  AND DISCRIMINATOR = 'PrimaryMovement'
  AND MOVEMENT_TYPE = 'ExPit'
  AND MOVEMENT_CLASSIFICATION = 'Expit Ore'
  AND MOVEMENT_SUBCLASSIFICATION = 'Expit Ore'
ORDER BY OBSERVED_AT, INTERNAL_ID
LIMIT 200001
